# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: rmcache
        name: remove cache
        description: Remove cache dirs that appear with testing
        entry: rm -rf dist/ *_cache/ .coverage
        language: system
        types: [text]
        pass_filenames: false
        stages: [pre-commit]
      - id: pytest
        name: test with pytest
        description: Test with pytest
        entry: pytest
        language: system
        types: [text]
        pass_filenames: false
        stages: [pre-commit]
      - id: bandit
        name: test with bandit
        description: Test with bandit
        entry: bandit -r src -ll
        language: system
        types: [text]
        pass_filenames: false
        stages: [pre-commit]
