name: testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Run pytest with coverage
      if: always()
      run: |
        pytest --cov-report term --cov-report=html
        coverate json -o CICD/coverage.json
    - name: Run bandit
      if: always()
      run: |
        bandit -r src --format json > CICD/bandit.json
    - name: Ruff
      run: |
        ruff check src --fix
    - name: Configure git
      if: always()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Add and commit CICD dir
      if: always()
      run: |
        git add CICD
        git commit -m "Add CICD dir"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}