name: testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Change to repository root
      run: cd ${{ github.workspace }}
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        python -m pip install pytest-cov
        python -m pip install -e .[dev]
    - name: Run pytest with coverage
      run: |
        pytest  --cov-reset --cov=src --cov-report=term --cov-report=json:./CICD/coverage.json ./tests
    - name: Run bandit
      run: |
        bandit -r src --format json > CICD/bandit.json
    - name: Ruff
      run: |
        ruff check src --fix
    - name: Doctests
      run: |
        python -m doctest -o ELLIPSIS -v src/tg_reader/*.py
    - name: Add and commit CICD dir
      uses: EndBug/add-and-commit@v9
      with:
        add: "CICD/"
        fetch: false
        push: true


